# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bracknell Code Club
email: admin@bracknellcodeclub.org.uk
description: >  
  Bracknell Code Club is a programming club aimed at 9-11 year olds living
  in the Bracknell Forest Council catchment area. Weekly sessions are held
  at local libraries, teaching children to program using Scratch and Python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.bracknellcodeclub.org.uk"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
